"""Add batch articles to the Build with Vish site (../buildwithvish) as guides with #read-<slug> pages.

    python scripts/publish_site.py out/batch-01 [/home/user/buildwithvish]

Writes src/content-posts.js (one GUIDES entry per article, appended to the existing list), makes sure
src/build.py includes it, then runs the site build so site/ is ready to commit.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import markdown

TYPE = {"Creator economy x AI": "creator", "Real workflows and prompts": "workflow", "Career and AI Ops pivot": "career",
        "AI tools that change marketing work": "guide", "Contrarian takes": "guide"}


def entry(post: Path, rank: int) -> dict | None:
    meta_f, art_f = post / "meta.json", post / "article.md"
    if not meta_f.exists():
        return None
    meta = json.loads(meta_f.read_text())
    long_html = post / "site-page" / f"{meta['slug']}.html"
    if long_html.exists():  # hand-written long page from an earlier round
        html = long_html.read_text()
    elif art_f.exists():
        md = re.sub(r"^# .*\n", "", art_f.read_text(), count=1)  # title is rendered by the site
        html = markdown.markdown(md, extensions=["extra", "sane_lists"])
    else:
        return None
    html = html.replace("<a href=", '<a target="_blank" rel="noopener" href=')
    words = len(re.sub(r"<[^>]+>", " ", html).split())
    excerpt = re.sub(r"\*", "", meta.get("subtitle") or meta.get("hook") or "")
    return {"slug": meta["slug"], "type": TYPE.get(meta.get("pillar"), "guide"), "tools": ["multi"], "level": "Beginner",
            "mins": max(3, round(words / 220)), "rank": rank, "fresh": True,
            "title": meta["title"], "excerpt": excerpt[:160], "body": html}


def main(batch: Path, site: Path) -> None:
    posts = sorted(p for p in batch.iterdir() if p.is_dir())
    extra = [batch.parent / "2026-10-06-eu-ai-text-watermark", batch.parent / "2026-10-06-chatgpt-image-ads", batch.parent / "2026-10-06-meta-creator-hub"]
    entries = [e for i, p in enumerate(posts + extra) if (e := entry(p, 100 + i))]
    js = ("/* Build with Vish x LinkedIn batch articles (generated by linkedin-carousel-studio scripts/publish_site.py). */\n"
          "const POSTS = " + json.dumps(entries, ensure_ascii=False, indent=1).replace("</", "<\\/") + ";\n"
          "{ const have = new Set(GUIDES.map((g) => g.slug)); GUIDES.push(...POSTS.filter((p) => !have.has(p.slug))); }\n")
    (site / "src" / "content-posts.js").write_text(js)
    b = site / "src" / "build.py"
    s = b.read_text()
    if "content-posts.js" not in s:
        s = s.replace('"content-extra.js", ', '"content-extra.js", "content-posts.js", ', 1)
        b.write_text(s)
    subprocess.run([sys.executable, "src/build.py"], cwd=site, check=True)
    print(f"{len(entries)} articles -> {site}/src/content-posts.js; site rebuilt")


if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2] if len(sys.argv) > 2 else "/home/user/buildwithvish"))
